module.exports = {
  headJs: [
    'js/lib/jquery.js',
    'js/lib/angular.js',
    'js/lib/angular-route.js',
    'js/lib/angular-cookies.js',
    'js/lib/angular-local-storage.js',
    'js/lib/ngDialog.js',
    'js/app.js',
    'js/services/auth_service.js',
    'js/providers/csrf.js',
    'js/controllers/main.js',
    'js/controllers/home.js',
    'js/controllers/sign_up.js',
    'js/controllers/page_not_found.js',
    'js/controllers/flash.js',
    'js/controllers/log_in.js',
    'js/controllers/create_league.js',
    'js/controllers/leagues.js',
    'js/controllers/league.js',
    'js/controllers/eula.js',
    'js/controllers/about.js',
    'js/controllers/privacy_policy.js',
    'js/controllers/reset_password.js',
    'js/controllers/reset_new_password.js',
    'js/directives/logged_in.js',
    'js/directives/no_click_focus.js',
    'js/directives/no_email_validation.js',
  ],
  finalJs: [
    'js/lib/bootstrap.js',
    'js/lib/lodash.js',
  ],
  css: [
    'css/bootstrap.css',
    'css/bootstrap-theme.css',
    'css/font-awesome.css',
    'css/ngDialog.css',
    'css/theme.css',
  ],
};
